apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-master-jenkins-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-jenkins
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-77f52137
